### ISSUE TITLE
 error: cannot find symbol import org.opencv.RNCustomCropPackage; 

### ISSUE THREAD

**Issue by shahzaibali-code** [Michaelvilleneuve/react-native-perspective-image-cropper#47]
C:\Users\Home\Desktop\react native2\cropapp\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:19: error: cannot find symbol
import org.opencv.RNCustomCropPackage;
                 ^
  symbol:   class RNCustomCropPackage
  location: package org.opencv
C:\Users\Home\Desktop\react native2\cropapp\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:69: error: cannot find symbol
      new RNCustomCropPackage(),
          ^
  symbol:   class RNCustomCropPackage
  location: class PackageList
Note: C:\Users\Home\Desktop\react native2\cropapp\android\app\src\debug\java\com\cropapp\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (C:\Users\Home\Desktop\react native2\cropapp\node_modules\execa\index.js:174:9)
    at C:\Users\Home\Desktop\react native2\cropapp\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\Home\Desktop\react native2\cropapp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Home\Desktop\react native2\cropapp\node_modules\@react-native-community\cli\build\index.js:186:9)

please help them to solve it 
if i put import fr.michaelvilleneuve.customcrop.RNCustomCropPackage;  in PackageList and after run project  then auto change  to import org.opencv.RNCustomCropPackage;

**Comment by Ahmad5448** [comment]
add react- native.config.js file in root of your project  and add these lines in it 
module.exports = {
    dependencies: {
      'react-native-perspective-image-cropper': {
        platforms: {
          android: {
            packageImportPath: 'import fr.michaelvilleneuve.customcrop.RNCustomCropPackage;',
          }
        }
      }
    }
  };

**Comment by Ahmad5448** [comment]
it will resolve your issue but you will face some other issues in future 📟

**Comment by shahzaibali-code** [comment]
@Ahmad5448 thanks bro
